from script.extra.playwright.base_actions.AllowCookiesAction import AllowCookiesAction
from script.extra.playwright.ErrorIndicators import ErrorIndicators
from script.extra.adapters.SettingAdapter import SettingAdapter
from script.models.Command import performed_command_count
from script.extra.exceptions import SuccessfulLogin
from script.extra.exceptions import *
from script.extra.helper import go_to_page
from script.extra.parsers.RequestPayloadFetcherParser import RequestPayloadFetcherParser
import random
import json
import re

max_login_retry = 10
'''
We removed your photo => Whenever see this message, should set 'avatar_changed' to 0
But we're checking if this happens in avatar changes and not in post uploads
'''

class BrowserLoginEvent:
    command = None
    errors = None
    listener = None
    graphql_captured = False
    login_messages = [
        'Phone number, username, or email',
        "Don't have an account",
        'Mobile number, username or email',
        "Allow the use of cookies",
        "Allow all cookies",
        'Enter the 6-digit code',
        "If you're unable to receive a login code from an authentication app",
        'Enter a 6-digit login code generated by',
        "Don't have an account",
        'suspect automated behavior',
        'suspect automated behaviour',
        'To prevent your account from being temporarily restricted',
        'Use another profile',
        'Choose if we process your data',
        'you can choose whether you consent to us processing',
        'Changes to How We Manage Data',
        'Review and Agree',
        'Continue as',
        'if we process your data for ads',
        "Confirm you're human",
        'Enter your mobile number',
        'We sent a code to WhatsApp',
        'Check your WhatsApp messages',
        'Enter the code we sent to your WhatsApp',
        'Enter confirmation code',
        'check the security code',
        "We couldn't connect to Instagram",

        'your password was incorrect',
        'password you entered is incorrect',

        'was a problem logging you into Instagram',
        'login information you entered is incorrect',
        'Choose a way to recover',
        "There's an issue and the page could not be loaded",
        'Enter the code we sent to',
        'Check your email',
        "Enter the 6-digit code we sent to the email",
        'We Detected An Unusual Login',
        "We've detected an unusual login attempt",
        'What happened',
        'We removed some content or messages',
        'Your Post Goes Against Our Community',
        'We removed your post because it goes against our',
        'Your account has been disabled',
        'We disabled your account',
        'We suspended your account',
        'You submitted an appeal',
        'It usually takes us just over a day to review your information',
        'Check your text messages',
        'Choose a way to confirm',
        'Upload your ID',
        'We need a photo of your official ID',
        'Enter your email',
        "We’ll send a confirmation code to this email",
        'Save info',
        'Turn On notif',

        'Add a phone number to get back into Instagram',
        "We will send a confirmation code via SMS to your phone",
        'confirm that you own this account',
        "You'll need to verify your identity",
        "Help us confirm you own this account",
        'Sorry, something went wrong',
        "working on getting this fixed as soon as we can",
        'Help us confirm it',
        "Help us confirm that it's you",
        'feedback_required',
        "feedback required",
        'Change your password to secure your account',
        'Someone may have your password',
        'Change Your Password to Secure Your Account',
        'Please log in to continue',

        'rust this device to skip the step',
        'Find friends and accounts you like'
        'Get fresh updates here',
        'trust this device to skip the step',

        'You can no longer request a review',
        'This content is no longer available',

        'Upload a verification selfie',
    ]

    logged_in_messages = [
        'we need you to agree to the following',
        'Here are some of the key ways we may use your data',
        'The messaging tab has',
        'Turn On notif',
        "Allow the use of cookies",
        "Allow all cookies",
        'Find friends and accounts you like',
        'Get fresh updates here'
        'Save info'
    ]

    pre_login_messages = [
        'The messaging tab has'
    ]

    def __init__(self, ig):
        self.ig = ig
        self.errors = ErrorIndicators(self.ig)
        self.graphql_captured = False
        self.ig.graphql_data = None
        self.login_counter = 0
        self.logged_in_counter = 0
        self.pre_login_counter = 0
        self.login_clicked = False
        self.two_fa_clicked = False
        self._add_response_listener()

    def _add_response_listener(self):
        """Attach response listener to capture GraphQL requests"""

        def on_response(response):
            if self.graphql_captured:
                return

            if '/graphql/query' not in response.url:
                return

            parser = RequestPayloadFetcherParser(response, self.ig)
            if parser.parse():
                self.graphql_captured = True
                self.ig.account.add_cli('[GraphQL] Captured successfully')

        self.listener = on_response
        self.ig.page.on('response', self.listener)

    def init(self):
        self.ig.account.add_cli('Starting Login ...')
        self.ig.page.goto('https://www.instagram.com', timeout=100000)
        self.ig.pause(5000, 6000)

        self.pre_login_check()
        self.login_check()

        while self.ig.is_visible_by_texts(self.login_messages):
            self.login_counter += 1

            self.ig.account.add_cli(f'login message is visible trying to pass for {self.login_counter} time ...')

            self.fill_username_password()
            self.two_fa_process()
            AllowCookiesAction(self.ig).start()
            self.errors.suspect_automate_behavior_handler()
            self.errors.use_another_profile()
            self.errors.choose_if_we_process_your_data()
            self.errors.changes_to_how_we_manage_data()
            self.errors.continue_as_handler()
            self.errors.choose_if_we_process_your_data_for_ads()
            self.errors.confirm_you_are_human_to_use_your_account()
            self.errors.enter_your_mobile_number()
            self.errors.we_sent_a_code_to_whatsapp()
            self.errors.enter_confirmation_code_handler()
            self.errors.check_the_security_code()
            self.errors.not_connect_to_the_internet()
            self.errors.password_is_incorrect_handler()
            self.errors.problem_logging_in_handler()
            self.errors.login_info_is_incorrect()
            self.errors.choose_a_way_to_recover()
            self.errors.page_could_not_be_loaded_handler()
            self.errors.fill_code_sent_to_email()
            self.unusual_login_detected()
            self.we_removed_some_content_or_messages_handler()
            self.your_post_goes_against_our_community_handler()
            self.errors.disabled_account_handler()
            self.errors.suspended_account_handler()
            self.errors.appeal_submitted_handler()
            self.errors.check_your_text_messages()
            self.errors.choose_a_way_to_confirm()
            self.errors.upload_your_id_handler()
            self.errors.enter_your_email_handler()
            self.errors.add_a_phone_number()
            self.errors.confirm_you_own_this_account()
            self.errors.we_are_working_on_getting_this_fixed()
            self.errors.help_us_confirm_its_you_handler()
            self.errors.feedback_required()
            self.errors.change_password_handler()
            self.errors.trust_this_device()
            self.errors.you_can_no_longer_request_a_review()
            self.errors.this_content_is_no_longer_available()
            self.errors.upload_a_verification_selfie()
            self.please_log_in_to_continue()
            self.find_friends_and_accounts_you_like()
            self.save_info()
            self.turn_on_notif()
            self.ig.pause(4500, 5000)

            if self.login_counter > max_login_retry:
                self.ig.account.add_cli('Max login attempts reached.')
                raise Exception('Max login attempts reached.')

        self.save_session()
        self.follow_suggested()

    def pre_login_check(self):
        while self.ig.is_visible_by_texts(self.pre_login_messages):
            self.pre_login_counter += 1
            self.ig.account.add_cli(
                f'Pre login message is visible trying to pass for {self.pre_login_counter} time ...')

            # Possible messages
            self.the_messaging_tab_has_a_new_look()

            if self.pre_login_counter > max_login_retry:
                self.ig.account.add_cli('Max Pre login attempts reached.')
                break

            self.ig.pause(1200, 1500)

    def login_check(self):

        try:

            if self.ig.page.locator('a[href="/"]').count() > 0:
                self.ig.account.add_cli('User logged in before, checking possible messages')

                while self.ig.is_visible_by_texts(self.logged_in_messages):
                    self.logged_in_counter += 1
                    self.ig.account.add_cli(
                        f'logged in messages is visible trying to pass for {self.logged_in_counter} time ...')

                    self.ig.account.add_cli(f"max_login_retry = {max_login_retry}")

                    self.we_need_you_to_agree_to_the_following_items()
                    self.the_messaging_tab_has_a_new_look()
                    self.turn_on_notif()
                    self.find_friends_and_accounts_you_like()
                    self.save_info()
                    AllowCookiesAction(self.ig).start()
                    self._capture_graphql_data()

                    if self.logged_in_counter > max_login_retry:
                        self.ig.account.add_cli('Max Pre logged in attempts reached.')
                        break

                    self.ig.pause(1000, 1200)

                self.save_session()
                raise SuccessfulLogin('Logged in successfully')

            return True

        except SuccessfulLogin as e:
            raise SuccessfulLogin('Logged in successfully')

        except Exception as e:
            self.ig.account.add_cli(f'Login failed: {e}')

        self.ig.pause(5000, 7000)

        self.ig.account.add_cli('Failed to reach Instagram direct inbox after 5 attempts.')
        raise Exception('Failed to reach Instagram direct inbox after 5 attempts.')

    def _capture_graphql_data(self):
        """Capture GraphQL data by liking and unliking a post on feed"""
        if self.graphql_captured and self.ig.graphql_data:
            self.ig.account.add_cli('[GraphQL] Already captured')
            return

        self.ig.account.add_cli('[GraphQL] Capturing via like action...')

        try:
            # Make sure we're on home feed
            if '/direct/' in self.ig.page.url or self.ig.page.url.rstrip('/') != 'https://www.instagram.com':
                go_to_page(self.ig, 'https://www.instagram.com/', 'Home')
                self.ig.pause(3000, 4000)

            # Scroll down to find posts
            scroll_amount = random.randint(300, 600)
            self.ig.page.mouse.wheel(0, scroll_amount)
            self.ig.pause(1500, 2500)

            if random.random() > 0.5:
                scroll_amount = random.randint(200, 400)
                self.ig.page.mouse.wheel(0, scroll_amount)
                self.ig.pause(1000, 1500)

            # Find and click a like button
            like_selectors = [
                'span.x1qfufaz div[role="button"]:has(svg[aria-label="Like"])',
                'div.x1ypdohk div[role="button"]:has(svg[aria-label="Like"])',
                'svg[aria-label="Like"]',
                'span svg[aria-label="Like"]',
                'div[role="button"] svg[aria-label="Like"]',
                'div[role="button"]:has(svg[aria-label="Like"])',
            ]

            like_clicked = False

            for selector in like_selectors:
                if like_clicked:
                    break

                try:
                    elements = self.ig.page.locator(selector)
                    count = elements.count()

                    if count > 0:
                        for i in range(min(count, 5)):
                            try:
                                element = elements.nth(i)
                                if element.is_visible():
                                    element.scroll_into_view_if_needed()
                                    self.ig.pause(500, 800)
                                    element.click(timeout=3000)
                                    self.ig.account.add_cli(f'[Like] Clicked element #{i}')
                                    like_clicked = True

                                    # Long pause after like to ensure GraphQL is captured
                                    self.ig.account.add_cli('[Like] Waiting 10 seconds to ensure GraphQL capture...')
                                    self.ig.pause(10000, 11000)
                                    break
                            except:
                                continue
                except:
                    continue

            if like_clicked:
                # Unlike immediately
                try:
                    self.ig.pause(1000, 1500)
                    unlike_selectors = [
                        'svg[aria-label="Unlike"]',
                        'div[role="button"]:has(svg[aria-label="Unlike"])',
                        'span svg[aria-label="Unlike"]',
                    ]

                    for selector in unlike_selectors:
                        try:
                            unlike_btn = self.ig.page.locator(selector).first
                            if unlike_btn.count() > 0 and unlike_btn.is_visible():
                                unlike_btn.click(timeout=2000)
                                break
                        except:
                            continue
                except:
                    pass

            # Log result
            if self.graphql_captured:
                self.ig.account.add_cli('[GraphQL] Capture successful')
            else:
                self.ig.account.add_cli('[GraphQL] Capture failed')

        except Exception as e:
            self.ig.account.add_cli(f'[GraphQL] Error: {str(e)[:50]}')

    def we_need_you_to_agree_to_the_following_items(self):
        is_visible = self.ig.is_visible_by_text('we need you to agree to the following') or self.ig.is_visible_by_text(
            'Here are some of the key ways we may use your data')

        if is_visible:
            self.ig.page.wait_for_selector('input[type="checkbox"][role="switch"]')

            toggles = self.ig.page.query_selector_all('input[type="checkbox"][role="switch"]')

            for i, toggle in enumerate(toggles, start=1):
                toggle.click()
                self.ig.pause(1000, 1500)

            self.ig.pause(3000, 4000)

            self.ig.page.get_by_role('button', name=re.compile(r'I agree', re.I)).click(timeout=3000)
            self.ig.pause(3000, 4000)
            self.ig.page.get_by_role('button', name=re.compile(r'Close', re.I)).click(timeout=3000)

    def two_fa_process(self):

        if self.two_fa_clicked:
            self.ig.account.add_cli('Two Factor Clicked Before')
            return True

        messages = [
            'Enter the 6-digit code',
            "If you're unable to receive a login code from an authentication app",
            'Enter a 6-digit login code generated by'
        ]

        if self.ig.is_visible_by_texts(messages):
            self.ig.account.add_cli('Two factor is visible ... ')

            try:
                self.ig.page.get_by_label('Security Code').press_sequentially(
                    self.ig.account.get_verification_code(),
                    delay=100,
                    timeout=6000
                )

            except:
                self.ig.account.add_cli('Security Code input dont exists trying second method ...')

                try:
                    input_box = self.ig.page.locator('input[name="verificationCode"]').first
                    input_box.wait_for(state="visible", timeout=6000)
                    input_box.fill(self.ig.account.get_verification_code())

                except Exception as e:
                    self.ig.account.add_cli('input[type="text"] dont exists trying Third method ...')

                    self.ig.page.get_by_label('Code').press_sequentially(
                        self.ig.account.get_verification_code(),
                        delay=100,
                        timeout=6000
                    )

            try:
                self.ig.page.get_by_role('button', name='Confirm').click(timeout=5000)
            except Exception as e:
                self.ig.page.get_by_role('button', name='Continue').click(timeout=5000)

            self.two_fa_clicked = True
            self.ig.account.add_cli('2FA confirm clicked')
            self.ig.pause(8000, 10000)

    def fill_username_password(self):

        if self.login_clicked:
            self.ig.account.add_cli("Login Clicked Before")
            return True

        input1 = self.ig.page.get_by_label('Phone number, username, or email')
        input2 = self.ig.page.get_by_label('Phone number, username or email address')
        input3 = self.ig.page.get_by_label('Mobile number, username or email')

        messages = [
            'Phone number, username, or email',
            "Don't have an account",
            'Phone number, username or email address',
            'Mobile number, username or email'
        ]

        if self.ig.is_visible_by_texts(messages):
            self.ig.account.add_cli("Username input appeared ... ")

            def fps(locator, text):
                locator.fill('')
                locator.press_sequentially(text, delay=100, timeout=8000)

            try:
                fps(input3, self.ig.account.username)
            except:
                try:
                    self.ig.account.add_cli('First locator didnt found')
                    fps(input2, self.ig.account.username)

                except:
                    try:
                        self.ig.account.add_cli('Second locator didnt found')
                        fps(input1, self.ig.account.username)
                    except:
                        self.ig.account.add_cli('Third locator didnt found')

            self.ig.pause(1500, 2000)

            fps(self.ig.page.get_by_label('Password'), self.ig.account.password)

            self.ig.pause(1500, 2000)

            try:
                self.ig.page.get_by_role('button', name='Log in').click(timeout=3000)
            except:
                self.ig.account.add_cli('First login locator failed')
                self.ig.page.locator('[aria-label="Log In"]').click(timeout=3000)

            self.login_clicked = True
            self.ig.pause(7000, 8000)

    def unusual_login_detected(self):

        messages = [
            'We Detected An Unusual Login',
            "We've detected an unusual login attempt"
        ]
        if self.ig.is_visible_by_texts(messages):
            self.ig.account.add_cli('Unusual Login Detected')

            if self.ig.is_visible_by_text("we'll send you a security code to verify your identity"):
                raise HelpUsConfirmItsYouError("we'll send you a security code")

            try:
                self.ig.page.get_by_role('button', name='This Was Me').click(timeout=3000)
            except:
                self.ig.page.get_by_role('button', name=re.compile(r'this was me', re.IGNORECASE)).click()

            self.ig.pause(5000, 6000)

    def we_removed_some_content_or_messages_handler(self):

        messages = [
            'What happened',
            'We removed some content or messages'
        ]
        if self.ig.is_visible_by_texts(messages):
            self.ig.account.add_cli('We removed some content or messages')

            try:
                self.ig.page.locator('div.wbloks_1[role="button"]').first.click(timeout=3000)
                self.ig.pause(4000, 5000)

                go_to_page(self.ig, 'https://www.instagram.com/', 'Home')

                self.ig.pause(3000, 4000)
            except Exception as e:
                self.ig.account.add_cli(str(e))

    def your_post_goes_against_our_community_handler(self):

        messages = [
            'Your Post Goes Against Our Community',
            'We removed your post because it goes against our',
        ]
        if self.ig.is_visible_by_texts(messages):
            self.ig.account.add_cli('Your Post Goes Against Our Community')

            try:
                self.ig.page.get_by_role('button', name='OK').first.click()
            except Exception as e:
                self.ig.page.locator(
                    'div.x1i10hfl.xjqpnuy.xa49m3k.xqeqjp1.x2hbi6w.x972fbf.xcfux6l.x1qhh985.xm0m39n.xdl72j9.x2lah0s.xe8uvvx.xdj266r.x11i5rnm.xat24cr.x1mh8g0r.x2lwn1j.xeuugli.xexx8yu'
                ).first.click()

            self.ig.pause(5000, 6000)

    def please_log_in_to_continue(self):
        if self.ig.is_visible_by_text('Please log in to continue'):
            self.ig.page.get_by_role('button', name='Log in').click(timeout=3000)
            self.ig.pause(1000, 2000)

    def save_info(self):
        if self.ig.is_visible_by_text('Save info'):
            try:
                self.ig.account.add_cli('Saving information ...')
                self.ig.page.get_by_role('button', name='Save info', exact=True).click(timeout=3500)
                self.ig.pause(5000, 6000)
            except:
                self.ig.account.add_cli("Save info doesn't exists")

    def turn_on_notif(self):
        if self.ig.is_visible_by_text('Turn On notif'):
            try:
                self.ig.page.get_by_role('button', name=re.compile(r'Turn On', re.IGNORECASE)).click()
                self.ig.pause(4000, 5000)
            except:
                self.ig.account.add_cli("Turn On doesn't exists")
                pass

    def the_messaging_tab_has_a_new_look(self):
        if self.ig.is_visible_by_text('The messaging tab has'):
            self.ig.page.get_by_role('button', name=re.compile(r'OK', re.IGNORECASE)).click()

    def find_friends_and_accounts_you_like(self):
        messages = [
            'Get fresh updates here',
            'Find friends and accounts you like'
        ]

        if self.ig.is_visible_by_texts(messages):
            # Try old method first (Next button)
            try:
                self.ig.page.get_by_role('button', name=re.compile(r'next', re.IGNORECASE)).click(timeout=3000)
                self.ig.pause(3000, 4000)
                return
            except:
                self.ig.page.get_by_role('button', name=re.compile(r'Follow', re.IGNORECASE)).click(timeout=3000)

                self.ig.account.add_cli('Next button not found, trying search and follow...')

            # Fallback: search and follow
            try:
                target = random.choice(['instagram', 'meta'])

                search_input = self.ig.page.get_by_placeholder(re.compile(r'search', re.IGNORECASE))
                search_input.click(timeout=3000)
                search_input.press_sequentially(target, delay=100)
                self.ig.pause(2000, 3000)

                # Click checkbox to select the account
                self.ig.page.locator('input[type="checkbox"][aria-label="Checkmark outline icon"]').first.click(timeout=5000)
                self.ig.account.add_cli(f'Selected {target} checkbox')
                self.ig.pause(1500, 2500)

                # Now Follow button should be enabled, click it
                self.ig.page.get_by_role('button', name=re.compile(r'^Follow$', re.IGNORECASE)).click(timeout=5000)
                self.ig.account.add_cli(f'Followed {target} from find friends page')
                self.ig.pause(3000, 4000)

            except Exception as e:
                self.ig.account.add_cli(f'Problem with find friends: {str(e)}')
                go_to_page(self.ig, 'https://www.instagram.com/', 'Home')
                self.ig.pause(3000, 4000)

    def save_session(self):
        self.ig.account.add_cli('Saving session ...')

        storage_state = self.ig.page.context.storage_state()
        storage_state_json = json.dumps(storage_state)
        self.ig.account.save_session(storage_state_json)

    def follow_suggested(self):

        if self.ig.is_visible_by_text('Suggested for you'):
            random_follow_number = random.randint(1, 2)
            follow_buttons = self.ig.page.query_selector_all('button:has-text("Follow")')

            selected_follow_button = random.sample(follow_buttons, random_follow_number)
            count = 0

            for button in selected_follow_button:
                count += 1
                self.ig.account.add_cli(f'Following suggested user for time: {count}')

                command = self.ig.account.create_command('follow', 'processing')
                try:
                    button.click()
                    command.update_cmd('state', 'success')
                    self.ig.account.add_cli('Lead followed successfully')

                except Exception as e:
                    self.ig.account.add_cli(f'Failed to follow suggested: {str(e)}')
                    command.update_cmd('state', 'fail')
                self.ig.pause(1000, 3500)

        self.ig.pause(2000, 3500)
